import type { Metadata } from "next";
import "./globals.css";
import Session from "../components/layout/Session";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import Theme from "@/components/layout/Theme";
import { Toaster } from "sonner";
import Query from "@/components/layout/Query";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Reflectify",

  description: "Generated by create-prisma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("font-sans", inter.variable)}
    >
      <Session>
        <body>
          <Toaster />

          <Theme>
            <Query>{children}</Query>
          </Theme>
        </body>
      </Session>
    </html>
  );
}
