import type { Metadata } from "next";
import "./globals.css";
import Session from "../components/layout/Session";

export const metadata: Metadata = {
  title: "Reflectify",
  description: "Generated by create-prisma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Session>
        <body>{children}</body>
      </Session>
    </html>
  );
}
